### ISSUE TITLE
WAIT YOU'RE ACTUALLY USING HISOCK??

### ISSUE THREAD

**Issue by SSS-Says-Snek** [sheepy0125/multiplayer-snake#1]
only way to talk cuz school didn't blocc github

**Comment by sheepy0125** [comment]
thanks for this very important issue. since it is an issue, i assume you don't like it. i will make sure to switch to a different thing, like the built-in socket module. /s

**Comment by SSS-Says-Snek** [comment]
[insert punching sheep gif]

**Comment by sheepy0125** [comment]
hey what you can close issues?
