### ISSUE TITLE
You know you don't need to specify the dependencies of the dependencies, right?

### ISSUE THREAD

**Issue by SSS-Says-Snek** [sheepy0125/multiplayer-snake#3]
hey at least this is on topic

**Comment by SSS-Says-Snek** [comment]
btw @sheepy0125 there's a builtin module named configparser :kekw:

**Comment by sheepy0125** [comment]
blame `pip freeze > requirements.txt` :)

**Comment by sheepy0125** [comment]
> btw @sheepy0125 there's a builtin module named configparser :kekw:

too late now, whoops!
